### ISSUE TITLE
crashes with a LOT of mods for no reason

### ISSUE THREAD

**Issue by Aabaddon** [Moutard3/fabric-realistic-inventory#4]
-- Head --
Thread: Render thread
Stacktrace:
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
	at java.base/java.util.Objects.checkIndex(Unknown Source)
	at java.base/java.util.ArrayList.get(Unknown Source)
	at net.minecraft.class_2371.get(class_2371.java:47)
	at net.minecraft.class_481.method_2466(class_481.java:644)
	at net.minecraft.class_481.method_25406(class_481.java:561)
	at net.minecraft.class_312.method_1605(class_312.java:100)
	at net.minecraft.class_437.method_25412(class_437.java:409)
	at net.minecraft.class_312.method_1601(class_312.java:100)
	at net.minecraft.class_312.method_22686(class_312.java:169)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:169)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:212)
Mixins in Stacktrace:
	net.minecraft.class_481:
		me.moutarde.realisticinventory.mixin.Creative.CreativeInventoryScreenAccessor (realistic-inventory.mixins.json)
		me.moutarde.realisticinventory.mixin.Creative.CreativeInventoryScreenMixin (realistic-inventory.mixins.json)
		dev.emi.trinkets.mixin.CreativeInventoryScreenMixin (trinkets.mixins.json)
		net.fabricmc.fabric.mixin.itemgroup.client.CreativeInventoryScreenMixin (fabric-item-group-api-v1.client.mixins.json)
	net.minecraft.class_312:
		net.fabricmc.fabric.mixin.screen.MouseMixin (fabric-screen-api-v1.mixins.json)
		net.mehvahdjukaar.supplementaries.mixins.fabric.MouseScrollMixin (supplementaries.mixins.json)
		com.tiviacz.travelersbackpack.mixin.MouseMixin (travelersbackpack.mixins.json)
		net.threetag.palladiumcore.mixin.fabric.MouseHandlerMixin (palladiumcore.mixins.json)
		dev.architectury.mixin.fabric.client.MixinMouseHandler (architectury.mixins.json)
		io.github.fabricators_of_create.porting_lib.mixin.client.MouseHandlerMixin (porting_lib_base.mixins.json)
		net.mehvahdjukaar.supplementaries.mixins.MouseHandlerMixin (supplementaries-common.mixins.json)
		com.railwayteam.railways.mixin.conductor_possession.MixinMouseHandler (railways-common.mixins.json)
	net.minecraft.class_437:
		net.fabricmc.fabric.mixin.screen.ScreenMixin (fabric-screen-api-v1.mixins.json)
		net.threetag.palladiumcore.mixin.fabric.ScreenMixin (palladiumcore.mixins.json)
		com.minelittlepony.common.mixin.MixinScreen (kirin.mixin.json)
		com.tterrag.blur.mixin.MixinScreen (mixins.blur.json)
		snownee.kiwi.mixin.client.ScreenMixin (kiwi.mixins.json)
		net.diebuddies.mixins.guiphysics.MixinScreen (physicsmod.mixins.json)
		dev.architectury.mixin.fabric.client.MixinScreen (architectury.mixins.json)
		net.fabricmc.fabric.mixin.screen.ScreenAccessor (fabric-screen-api-v1.mixins.json)
		net.diebuddies.mixins.cloth.MixinScreen (physicsmod.mixins.json)
		dev.imb11.flow.mixin.ScreenAccessor (flow.mixins.json)
		me.pieking1215.invmove.fabric_like.mixin.client.OverlayMixin (invmove-fabric-like.mixins.json)
		io.github.fabricators_of_create.porting_lib.mixin.accessors.client.accessor.ScreenAccessor (porting_lib_accessors.mixins.json)
		me.pieking1215.invmove.mixin.client.BackgroundMixin (invmove.mixins.json)
	com.mojang.blaze3d.systems.RenderSystem:
		qouteall.imm_ptl.core.mixin.client.render.MixinRenderSystem_Fog (imm_ptl.mixins.json)
		qouteall.imm_ptl.core.mixin.client.render.MixinRenderSystem_Clipping (imm_ptl.mixins.json)
		io.github.foundationgames.animatica.mixin.RenderSystemMixin (animatica.mixins.json)
		com.jozufozu.flywheel.mixin.RenderTexturesMixin (flywheel.mixins.json)

**Comment by Mdbgamer** [comment]
Yeah, it seems to crash just straight out of the gate.

**Comment by Mdbgamer** [comment]
I just tried to load the mod without any other mods and uh... I was getting maybe 1 frame per 10 seconds **_In the main menu._**

Not in a world. Freshly loaded. No other mods, just the Fabric API. And it was taking an eternity to get through the main menu settings.

Something is seriously *wrong* with this mod.
